title:              "이다용 DevLog"
email:              "dayongbz@gmail.com"
description:        "이다용의 개발일지 입니다~"
author:             "이다용"
name:               "이다용"
locale:             "ko-KR"
baseurl:            ""
url:                "https://dayongbz.github.io"

# Social Profiles
github_username:    "dayongbz"
facebook_username:  "이다용"

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
  
remote_theme : BlackrockDigital/startbootstrap-clean-blog-jekyll
