title: 이다용 Dev_Log
email: dayongbz@gmail.com
description: 이다용 개발 블로그입니다.
author: 이다용
baseurl: ""
url: "https://dayongbz.github.io"

# Social Profiles
github_username: dayongbz

# Add your google-analytics ID here to activate google analytics
google_analytics: UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
